import type { TimelineEvent } from './types';

/** "Origins": four thousand years of the unicorn, in chronological order. */
export const timeline: TimelineEvent[] = [
  {
    id: 'indus',
    marker: '2600 BCE',
    date: 'c. 2600–1900 BCE',
    title: 'The seals of the Indus',
    body: 'In Mohenjo-daro and Harappa, a one-horned, bull-like beast is the most common image on the thousands of stamp seals found — usually shown before a mysterious ritual stand. What it meant, no one can read: the script beside it is still undeciphered.',
    artworkId: 'indus-seal',
  },
  {
    id: 'ctesias',
    marker: '400 BCE',
    date: 'c. 400 BCE',
    title: 'Ctesias’ wild asses of India',
    body: 'The Greek physician Ctesias of Cnidus, who never visited India, records “wild asses” as large as horses with white bodies, dark-red heads and blue eyes. Their single horn is white at the base, black in the middle and crimson at the tip — and drinking from it protects against poison.',
  },
  {
    id: 'aristotle',
    marker: '350 BCE',
    date: '4th century BCE',
    title: 'Aristotle takes note',
    body: 'In his studies of animals, Aristotle names two one-horned creatures — the oryx and the “Indian ass” — lending the unicorn the most respectable citation in the ancient world.',
  },
  {
    id: 'pliny',
    marker: '77 CE',
    date: '77 CE',
    title: 'Pliny’s monoceros',
    body: 'Pliny the Elder’s <cite>Natural History</cite> describes the fiercest animal of all: a horse’s body, a stag’s head, an elephant’s feet, a boar’s tail, and one black horn two cubits long. It “cannot be taken alive.”',
  },
  {
    id: 'physiologus',
    marker: '300 CE',
    date: '2nd–4th century CE',
    title: 'The Physiologus',
    body: 'An anonymous Greek text from Alexandria gives the legend its most famous twist: no hunter can catch the unicorn — but it will lay its head in the lap of a virgin. Christian readers made the tale an allegory of Christ, and the image spread across Europe.',
  },
  {
    id: 'bestiaries',
    marker: '1200',
    date: 'c. 1200',
    title: 'The bestiaries',
    body: 'Illuminated “books of beasts”, like the Aberdeen Bestiary, place the unicorn beside the lion and the elephant as a real animal — drawn small, goat-like and gilded, a creature of moral lessons rather than zoology.',
    artworkId: 'bestiary',
  },
  {
    id: 'qilin-giraffe',
    marker: '1414',
    date: '1414',
    title: 'A giraffe for the emperor',
    body: 'Envoys from Bengal bring a giraffe to the Ming court in Nanjing. Courtiers hail it as a <em>qilin</em> — the auspicious one-horned beast said to appear only under a wise ruler — and the court painter Shen Du records the event.',
    artworkId: 'giraffe',
  },
  {
    id: 'tapestries',
    marker: '1500',
    date: 'c. 1495–1505',
    title: 'The great tapestries',
    body: 'Weavers of the Southern Netherlands produce the two most famous unicorn images ever made: the seven <cite>Unicorn Tapestries</cite> now at The Met Cloisters in New York, and the six <cite>Lady and the Unicorn</cite> hangings now in Paris’s Musée de Cluny.',
    artworkId: 'lady-sight',
  },
  {
    id: 'raphael',
    marker: '1505',
    date: 'c. 1505–06',
    title: 'Raphael’s hidden unicorn',
    body: 'Raphael paints a young woman holding a tiny unicorn, a symbol of chastity. Later painters covered it over to turn her into Saint Catherine; the unicorn was only rediscovered during a restoration in the 1930s.',
    artworkId: 'raphael',
  },
  {
    id: 'lion-and-unicorn',
    marker: '1603',
    date: '1603',
    title: 'The lion and the unicorn',
    body: 'Scotland’s royal arms had been held by unicorns since the 15th century. When James VI of Scotland inherits England’s throne, the Scottish unicorn joins the English lion on the royal coat of arms — where, chained, it still stands.',
  },
  {
    id: 'monoceros',
    marker: '1612',
    date: '1612',
    title: 'Into the stars',
    body: 'The Dutch cartographer Petrus Plancius charts <em>Monoceros</em>, a faint constellation between Orion and Hydra. The unicorn has been in the night sky ever since — look up at the top of this page.',
  },
  {
    id: 'ole-worm',
    marker: '1638',
    date: '1638',
    title: 'Ole Worm and the narwhal',
    body: 'For centuries, “unicorn horns” — alicorns — sold for more than their weight in gold as antidotes to poison. The Danish naturalist Ole Worm demonstrates that they are in fact the tusks of the Arctic narwhal.',
    artworkId: 'wormianum',
  },
  {
    id: 'danish-throne',
    marker: '1671',
    date: '1662–1671',
    title: 'A throne of “horn”',
    body: 'Unconvinced, or simply dazzled, Denmark’s kings commission a coronation throne built from narwhal tusks — the Throne Chair of Denmark, still guarded by three silver lions at Rosenborg Castle.',
    artworkId: 'narwhal',
  },
  {
    id: 'elasmotherium',
    marker: '39,000 BP',
    date: 'Rediscovered 2018',
    title: 'The Siberian “unicorn”',
    body: 'Fossils show that <em>Elasmotherium sibiricum</em> — a woolly, multi-tonne rhinoceros with a single great horn — survived on the Eurasian steppe until at least 39,000 years ago, sharing the world with early modern humans.',
  },
];
